language: python

python:
  - "3.6"

cache: pip

install:
  - cd python/package_template
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - python setup.py install
  - cd ..

script:
  - pytest -vv --cov package_template/foobar package_template/foobar
  - flake8 package_template/foobar
